typography_spectrum: 0.55045
color:
  brandColors:
    - '#0069b4'
    - '#fc4349'
    - '#ffffff'
    - '#0000ff'
    - '#004080'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49953
analytics:
  google: null
  facebook: null
  twitter: null
name: enhancedpower
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: about
    type: external
favicon: null
title: Enhanced Power Services Limited
purpose: []
