name: enhancedpower
favicon: null
layout_spectrum: 0.7433382240124047
typography_spectrum: 0.12759262952022254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.45349167799577117
  lightness: 0.6804672640282661
  saturation: 0.276147527853027
  rhythmicContrast: 0.06499604554846883
purpose: []
