name: enhancedpower
favicon: null
layout_spectrum: 0.49953
typography_spectrum: 0.55045
title: Enhanced Power Services Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0069b4'
    - '#fc4349'
    - '#ffffff'
    - '#0000ff'
    - '#004080'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
